In [1]:
import numpy as np

In [2]:
m = np.matrix([[1, -2, -3], [0, 4, 5], [7, 8, -9]])
m

matrix([[ 1, -2, -3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [3]:
# 转置
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [-3,  5, -9]])

In [4]:
# 逆矩阵
m.I

matrix([[ 1.22580645,  0.67741935, -0.03225806],
        [-0.56451613, -0.19354839,  0.08064516],
        [ 0.4516129 ,  0.35483871, -0.06451613]])

In [5]:
v = np.matrix([[2], [3], [4]])
v

matrix([[2],
        [3],
        [4]])

In [6]:
# (3 ✖ 3) * (3 ✖ 1) = (3 ✖ 1)
m * v

matrix([[-16],
        [ 32],
        [  2]])

In [7]:
# 求行列式
np.linalg.det(m)

-62.00000000000001

In [8]:
# 特征值
np.linalg.eigvals(m)

array([-10.36548788,   1.14596426,   5.21952362])

In [9]:
# 求m·x = v
x = np.linalg.solve(m, v)
x

matrix([[ 4.35483871],
        [-1.38709677],
        [ 1.70967742]])

In [10]:
m * x

matrix([[2.],
        [3.],
        [4.]])

In [11]:
v

matrix([[2],
        [3],
        [4]])