<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy的concate函数" data-toc-modified-id="Numpy的concate函数-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy的concate函数</a></span></li><li><span><a href="#pandas的concat函数" data-toc-modified-id="pandas的concat函数-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>pandas的concat函数</a></span><ul class="toc-item"><li><span><a href="#Series" data-toc-modified-id="Series-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Series</a></span><ul class="toc-item"><li><span><a href="#join参数，可以是inner或outer，默认为outer，" data-toc-modified-id="join参数，可以是inner或outer，默认为outer，-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>join参数，可以是inner或outer，默认为outer，</a></span></li><li><span><a href="#join_axes参数用于指定连接轴" data-toc-modified-id="join_axes参数用于指定连接轴-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>join_axes参数用于指定连接轴</a></span></li><li><span><a href="#keys参数，在行方向上连接，为多层索引，在列方向上连接，为DataFrame的列头" data-toc-modified-id="keys参数，在行方向上连接，为多层索引，在列方向上连接，为DataFrame的列头-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>keys参数，在行方向上连接，为多层索引，在列方向上连接，为DataFrame的列头</a></span></li></ul></li><li><span><a href="#DataFrame" data-toc-modified-id="DataFrame-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>DataFrame</a></span><ul class="toc-item"><li><span><a href="#keys参数，行：多层索引，列：列头" data-toc-modified-id="keys参数，行：多层索引，列：列头-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>keys参数，行：多层索引，列：列头</a></span></li><li><span><a href="#ignore_index=True-不保留索引，生成一个新的index" data-toc-modified-id="ignore_index=True-不保留索引，生成一个新的index-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>ignore_index=True 不保留索引，生成一个新的index</a></span></li></ul></li></ul></li></ul></div>

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## Numpy的concate函数

In [2]:
arr = np.arange(12).reshape((3, 4))

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.concatenate([arr, arr]) # 默认在行方向上连接

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.concatenate([arr, arr], axis=1) # axis=1 在列方向上连接

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

## pandas的concat函数

### Series

In [6]:
s1 = Series([0, 1], index=['a', 'b'])

In [7]:
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])

In [8]:
s3 = Series([5, 6], index=['f', 'g'])

In [9]:
s1

a    0
b    1
dtype: int64

In [10]:
s2

c    2
d    3
e    4
dtype: int64

In [11]:
s3

f    5
g    6
dtype: int64

In [12]:
pd.concat([s1, s2, s3]) # 在行方向上连接，返回的是一个Series

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [13]:
pd.concat([s1, s2, s3], axis=1) # 在列方向上连接，返回的是一个DataFrame

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [14]:
s4 = pd.concat([s1, s3]) # 行方向上进行连接，返回的是Series

In [15]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [16]:
s1

a    0
b    1
dtype: int64

In [17]:
pd.concat([s1, s4], axis=1) # 列方向上进行连接，返回的是DataFrame

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

#### join参数，可以是inner或outer，默认为outer，

In [18]:
pd.concat([s1, s4], axis=1, join='inner') # 内连接

0  1
a  0  0
b  1  1

#### join_axes参数用于指定连接轴

In [19]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']]) # join_axes 用于指定连接其他轴向的轴

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

#### keys参数，在行方向上连接，为多层索引，在列方向上连接，为DataFrame的列头

In [20]:
result = pd.concat([s1, s2, s3], keys=['one', 'two', 'three']) # 在行方向上连接，keys参数用于在连接轴向上创建一个多层索引

In [21]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [22]:
result.unstack() # 行→列，内层

a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [23]:
result.unstack(0) # 行→列，外层

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [24]:
# 沿着轴向axis=1连接Series时，keys参数成为DataFrame的列头
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

### DataFrame

In [25]:
df1 = DataFrame(np.arange(6.).reshape((3, 2)), 
                index=['a', 'b', 'c'],
                columns=['one', 'two'])

In [26]:
df2 = DataFrame(5 + np.arange(4).reshape((2, 2)),
                index=['a', 'c'],
                columns=['three', 'four'])

In [27]:
df1

one  two
a  0.0  1.0
b  2.0  3.0
c  4.0  5.0

In [28]:
df2

three  four
a      5     6
c      7     8

#### keys参数，行：多层索引，列：列头

In [29]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2']) # 列方向上连接，keys参数

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1      level2     
     one  two  three four
a    0.0  1.0    5.0  6.0
b    2.0  3.0    NaN  NaN
c    4.0  5.0    7.0  8.0

In [30]:
pd.concat([df1, df2], keys=['level1', 'level2'])

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


four  one  three  two
level1 a   NaN  0.0    NaN  1.0
       b   NaN  2.0    NaN  3.0
       c   NaN  4.0    NaN  5.0
level2 a   6.0  NaN    5.0  NaN
       c   8.0  NaN    7.0  NaN

In [31]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1      level2     
     one  two  three four
a    0.0  1.0    5.0  6.0
b    2.0  3.0    NaN  NaN
c    4.0  5.0    7.0  8.0

In [32]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],
          names=['upper', 'lower'])

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


upper level1      level2     
lower    one  two  three four
a        0.0  1.0    5.0  6.0
b        2.0  3.0    NaN  NaN
c        4.0  5.0    7.0  8.0

In [33]:
df1 = DataFrame(np.random.randn(3, 4),
                columns=['a', 'b', 'c', 'd'])

In [34]:
df2 = DataFrame(np.random.randn(2, 3), 
                columns=['b', 'd', 'a'])

In [35]:
df1

a         b         c         d
0  1.471210 -0.404648  0.234431  0.453577
1 -0.117971 -1.084806  0.346403  0.479013
2 -0.726858 -0.842502  2.289636 -1.252166

In [36]:
df2

b        d         a
0 -1.458561 -0.51385  0.294615
1  0.545951  0.67129 -0.042931

In [37]:
pd.concat([df1, df2]) # 行方向上连接

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0  1.471210 -0.404648  0.234431  0.453577
1 -0.117971 -1.084806  0.346403  0.479013
2 -0.726858 -0.842502  2.289636 -1.252166
0  0.294615 -1.458561       NaN -0.513850
1 -0.042931  0.545951       NaN  0.671290

#### ignore_index=True 不保留索引，生成一个新的index

In [38]:
pd.concat([df1, df2], ignore_index=True) # 不保留索引，生成一个新的index

C:\Users\z\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0  1.471210 -0.404648  0.234431  0.453577
1 -0.117971 -1.084806  0.346403  0.479013
2 -0.726858 -0.842502  2.289636 -1.252166
3  0.294615 -1.458561       NaN -0.513850
4 -0.042931  0.545951       NaN  0.671290