<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np

In [2]:
arr = np.random.randn(6)

In [3]:
arr

array([ 2.11102096, -0.18679917,  0.88515614,  0.57340061, -0.49522975,
       -1.09783509])

In [4]:
arr.sort()

In [5]:
arr

array([-1.09783509, -0.49522975, -0.18679917,  0.57340061,  0.88515614,
        2.11102096])

In [6]:
arr = np.random.randn(5, 3)

In [7]:
arr

array([[-0.68972823, -1.75765465, -0.94915994],
       [ 1.29834401, -0.17277106,  0.95407737],
       [-0.39318116, -1.63896031,  1.80745944],
       [ 0.11670445, -0.07358937, -0.84398532],
       [-0.3666959 , -0.05400101, -0.85568735]])

In [8]:
arr.sort(1) # 对每一行的数据进行排序

In [9]:
arr

array([[-1.75765465, -0.94915994, -0.68972823],
       [-0.17277106,  0.95407737,  1.29834401],
       [-1.63896031, -0.39318116,  1.80745944],
       [-0.84398532, -0.07358937,  0.11670445],
       [-0.85568735, -0.3666959 , -0.05400101]])

In [10]:
arr = np.random.randn(5, 3)
arr

array([[ 1.55342247,  0.76803027,  0.33208738],
       [ 0.53776912, -0.5619963 ,  0.46157135],
       [-1.05170582,  1.4990647 , -0.77099922],
       [ 0.10993628, -1.42694953, -0.13424298],
       [ 0.85384956, -0.24151062,  1.01492928]])

In [11]:
arr.sort(0) # 对每一列的数据进行排序

In [12]:
arr

array([[-1.05170582, -1.42694953, -0.77099922],
       [ 0.10993628, -0.5619963 , -0.13424298],
       [ 0.53776912, -0.24151062,  0.33208738],
       [ 0.85384956,  0.76803027,  0.46157135],
       [ 1.55342247,  1.4990647 ,  1.01492928]])

In [13]:
large_arr = np.random.randn(1000)

In [14]:
large_arr.sort()

In [15]:
large_arr[int(0.05 * len(large_arr))] # 5% 分位数

-1.585390367389528