<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
cond = np.array([True, False, True, True, False])

In [4]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

In [5]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [6]:
result = np.where(cond, xarr, yarr)

In [7]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [8]:
arr = np.random.randn(4, 4)

In [9]:
arr

array([[-0.47955021, -1.33592226, -0.11868151, -0.16497771],
       [-0.43739841, -0.33478224, -0.09324296, -0.95489123],
       [-0.72370747,  2.0939028 , -0.68139556, -0.35630916],
       [-1.32318962, -0.75518229,  1.38833071, -1.3141372 ]])

In [10]:
arr > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [11]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2, -2],
       [-2, -2, -2, -2],
       [-2,  2, -2, -2],
       [-2, -2,  2, -2]])

In [12]:
# 仅将正值设为2
np.where(arr > 0, 2, arr)

array([[-0.47955021, -1.33592226, -0.11868151, -0.16497771],
       [-0.43739841, -0.33478224, -0.09324296, -0.95489123],
       [-0.72370747,  2.        , -0.68139556, -0.35630916],
       [-1.32318962, -0.75518229,  2.        , -1.3141372 ]])