<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#np.unique()-返回数组中的唯一值排序后形成的数组" data-toc-modified-id="np.unique()-返回数组中的唯一值排序后形成的数组-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>np.unique() 返回数组中的唯一值排序后形成的数组</a></span></li><li><span><a href="#np.in1d()-检查一个数组中的值是否在另一个数组中，并返回一个布尔值数组" data-toc-modified-id="np.in1d()-检查一个数组中的值是否在另一个数组中，并返回一个布尔值数组-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>np.in1d() 检查一个数组中的值是否在另一个数组中，并返回一个布尔值数组</a></span></li></ul></div>

In [1]:
import numpy as np

# np.unique() 返回数组中的唯一值排序后形成的数组

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [4]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [5]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [6]:
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [7]:
np.unique(ints)

array([1, 2, 3, 4])

In [8]:
sorted(set(names))

['Bob', 'Joe', 'Will']

# np.in1d() 检查一个数组中的值是否在另一个数组中，并返回一个布尔值数组

In [9]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [10]:
np.in1d(values, [2, 3, 6]) # values数组中的值是否在[2, 3, 6]中

array([ True, False, False,  True,  True, False,  True])