<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np

In [2]:
# 5×4 数组
arr = np.random.randn(5, 4)

In [3]:
arr

array([[-1.3300644 ,  0.03564532, -1.22942618,  1.03263149],
       [-0.91642589, -1.0252577 ,  1.13237458,  2.76076224],
       [ 0.45062124,  0.63965193, -0.60665629, -0.49760845],
       [ 0.27168125,  2.0450027 , -0.06803927,  0.36588708],
       [ 0.38625124,  0.58108771, -0.83481453,  0.76641843]])

In [4]:
# 所有数的平均值
arr.mean()

0.19798612502181392

In [5]:
np.mean(arr)

0.19798612502181392

In [6]:
arr.sum()

3.9597225004362784

In [7]:
np.sum(arr)

3.9597225004362784

In [8]:
arr.mean(axis=0) # 沿着列方向求平均，4个元素

array([-0.22758731,  0.45522599, -0.32131234,  0.88561816])

In [9]:
arr.mean(axis=1) # 沿着行方向求平均，5个元素

array([-0.37280344,  0.48786331, -0.00349789,  0.65363294,  0.22473571])

In [10]:
arr.sum(axis=0) # 沿着列方向求和，4个元素

array([-1.13793655,  2.27612996, -1.6065617 ,  4.42809079])

In [11]:
arr = np.arange(7)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
arr.cumsum() # 累积和

array([ 0,  1,  3,  6, 10, 15, 21], dtype=int32)

In [14]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

In [15]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr.cumsum(axis=0) # 沿着列方向求累积和

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [17]:
arr.cumsum(axis=1) # 沿着行方向求累积和

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [18]:
arr.cumprod(axis=0) # 沿着列方向求累积积

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [19]:
arr.cumprod(axis=1) # 沿着行方向求累积积

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)