<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.],
              [4., 5., 6.]])

In [3]:
y = np.array([[6., 23.],
              [-1, 7],
              [8, 9]])

In [4]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [6]:
x.dot(y) # x·y 矩阵乘法

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [9]:
x @ np.ones(3)

array([ 6., 15.])

In [10]:
from numpy.linalg import inv, qr

In [11]:
X = np.random.randn(5, 5)

In [12]:
mat = X.T.dot(X) # X.T·X

In [13]:
inv(mat) # 求逆

array([[  92.50802841,  147.73938741,  -31.6624613 , -190.54580929,
         120.90098936],
       [ 147.73938741,  238.78559219,  -51.06638369, -307.57531557,
         195.4904419 ],
       [ -31.6624613 ,  -51.06638369,   11.22397802,   65.78426841,
         -41.88742174],
       [-190.54580929, -307.57531557,   65.78426841,  396.59492589,
        -251.80105103],
       [ 120.90098936,  195.4904419 ,  -41.88742174, -251.80105103,
         160.41731547]])

In [14]:
mat.dot(inv(mat)) # mat·(mat)-1

array([[ 1.00000000e+00, -3.13717241e-15, -1.07067585e-15,
         1.35377040e-14,  1.44355429e-14],
       [ 8.64218738e-14,  1.00000000e+00, -3.15918408e-14,
        -5.29468911e-13, -4.45440205e-14],
       [ 1.30796855e-14,  1.55637529e-14,  1.00000000e+00,
         1.84661058e-14,  2.05516952e-14],
       [-9.98566482e-14,  1.58490968e-14,  1.96200618e-14,
         1.00000000e+00, -9.74488352e-14],
       [-2.36063350e-14,  8.06814200e-14, -1.30860438e-14,
        -1.65719984e-14,  1.00000000e+00]])

In [15]:
q, r = qr(mat) # QR分解

In [16]:
r

array([[-1.29427044e+00, -1.47992100e+00, -1.16345157e+00,
        -2.03551527e+00, -7.20880116e-01],
       [ 0.00000000e+00, -6.92788818e+00,  3.88018495e-01,
        -3.55527394e+00,  2.96553313e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.46354206e+00,
        -2.71663233e-03, -9.09531708e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.25471885e+00, -1.97451642e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.63774574e-03]])